# Generated by Django 5.1.2 on 2025-03-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
